/**:
  ros__parameters:
    wait_sec_between_publish: 2
    publish_topic: "/forward_position_controller/commands"

    goal_names: ["pos1", "pos2", "pos3", "pos4"]

    pos1: [ 0.6, 0.2, -0.8, 0.0, 0.0,  -0.6, -0.2, -0.8, 0.0, 0.0,   0.0,0.0,0.0,0.0,0.0,0.0,   0.0,0.0,0.0,0.0,0.0,0.0 ]
    pos2: [ 0.0, 0.0, -0.8, 0.0, 0.0,   0.0, 0.0, -0.8, 0.0, 0.0,   0.0,0.0,0.0,0.0,0.0,0.0,   0.0,0.0,0.0,0.0,0.0,0.0 ]
    pos3: [-0.6,-0.2, -0.8, 0.0, 0.0,   0.6, 0.2, -0.8, 0.0, 0.0,   0.0,0.0,0.0,0.0,0.0,0.0,   0.0,0.0,0.0,0.0,0.0,0.0 ]
    pos4: [ 0.0, 0.0, -0.8, 0.0, 0.0,   0.0, 0.0, -0.8, 0.0, 0.0,   0.0,0.0,0.0,0.0,0.0,0.0,   0.0,0.0,0.0,0.0,0.0,0.0 ]


