controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - l_sho_pitch
      - l_sho_roll
      - l_el
      - l_wst
      - l_grp
      - r_sho_pitch
      - r_sho_roll
      - r_el
      - r_wst
      - r_grp
      - l_hip_yaw
      - l_hip_roll
      - l_hip_pitch
      - l_knee
      - l_ank_pitch
      - l_ank_roll
      - r_hip_yaw
      - r_hip_roll
      - r_hip_pitch
      - r_knee
      - r_ank_pitch
      - r_ank_roll
      - head_pan
      - head_tilt
    interface_name: position
